/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceMarketingRouteImport } from './routes/performance-marketing'
import { Route as IndexRouteImport } from './routes/index'

const PerformanceMarketingRoute = PerformanceMarketingRouteImport.update({
  id: '/performance-marketing',
  path: '/performance-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/performance-marketing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/performance-marketing'
  id: '__root__' | '/' | '/performance-marketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerformanceMarketingRoute: typeof PerformanceMarketingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance-marketing': {
      id: '/performance-marketing'
      path: '/performance-marketing'
      fullPath: '/performance-marketing'
      preLoaderRoute: typeof PerformanceMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerformanceMarketingRoute: PerformanceMarketingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
